sudo: true
dist: trusty

language: cpp
compiler: gcc

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
- sudo apt-get -y install docker-ce

script: 
   - docker build -t dit168grp12 -f Dockerfile .

after_success:
    if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker tag dit168grp12 $DOCKER_USERNAME/dit168grp12:latest;
    docker push $DOCKER_USERNAME/dit168grp12:latest;
fi
