version: '2'
services:
    odsupercomponent:
        image: seresearch/2018-dit-168:v0.3.5-armhf
        network_mode: "host"
        restart: always
        volumes:
        - .:/opt/miniature.data
        command: "/opt/od4/bin/odsupercomponent --cid=230 --configuration=/opt/miniature.data/configuration"

    odforps4:
        image: seresearch/2018-dit-168:v0.3.5-armhf
        network_mode: "host"
        restart: always
        volumes:
        - .:/opt/miniature.data
        command: "/opt/od4/bin/odsupercomponent --cid=232 --configuration=/opt/miniature.data/configuration"

    proxy-miniature-pwm-motor:
        image: seresearch/2018-dit-168:v0.3.5-armhf
        depends_on:
        - odsupercomponent
        network_mode: "host"
        restart: always
        privileged: true
        volumes:
        - /sys/:/sys/
        - /dev/:/dev/
        command: "/opt/opendlv.miniature/bin/opendlv-proxy-miniature-pwm-motor --cid=230 --freq=50 --id=1"

    # Your microservice.
    proxy-miniature-ps4controller:
        image: seresearch/2018-dit-168:v0.3.5-armhf
        depends_on:
        - proxy-miniature-pwm-motor
        network_mode: "host"
        devices:
        - "/dev/input/js0:/dev/input/js0"
        command: "/opt/opendlv.miniature/bin/opendlv-proxy-miniature-ps4controller --cid=232 --freq=10"
      
    device-ultrasonic-srf08-front:
        image: chalmersrevere/opendlv-device-ultrasonic-srf08-armhf:v0.0.6
        network_mode: "host"
        privileged: true
        volumes:
          - /dev/i2c-1:/dev/i2c-1
        command: "/usr/bin/opendlv-device-ultrasonic-srf08 --dev=/dev/i2c-1 --bus-address=112 --cid=231 --freq=5"

    interceptor:
        image: internal
        network_mode: "host"
        restart: always
        command: "/opt/Interceptor --cid=232 --freq=10"

    web-interface:
        image: web
        network_mode: "host"
        ports:
        - "5001:5001"
        restart: always
        privileged: true
        command: "--cid=230 --freq=5"

#    v2v-interface:
 #      image: v2vbuild
  #     depends_on:
   #    - proxy-miniature-pwm-motor
    #   network_mode: "host"
     #  command: "/opt/V2V.Service --cid=230 --freq=10"
    
#    device-ultrasonic-srf08-rear:
 #       image: chalmersrevere/opendlv-device-ultrasonic-srf08-armhf:v0.0.6
  #      network_mode: "host"
   #     privileged: true
    #    volumes:
     #     - /dev/i2c-1:/dev/i2c-1
      #  command: "/usr/bin/opendlv-device-ultrasonic-srf08 --dev=/dev/i2c-1 --bus-address=112 --cid=111 --verbose=1 --freq=5 --id=1"
